# Generated by Django 6.0.6 on 2026-06-24 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='desciption',
        ),
        migrations.RemoveField(
            model_name='note',
            name='Course',
        ),
        migrations.AddField(
            model_name='note',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notes.course'),
            preserve_default=False,
        ),
    ]
