# Generated by Django 6.0.6 on 2026-06-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_course_desciption_remove_note_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notes/files/'),
        ),
    ]
