# Generated by Django 6.0.6 on 2026-07-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.CharField(choices=[('exam', 'امتحان'), ('exercise', 'تمرین'), ('project', 'پروژه'), ('lecture', 'جزوه')], default='lecture', max_length=20),
        ),
    ]
