# Generated by Django 6.0.6 on 2026-07-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='price_type',
            field=models.CharField(choices=[('free', 'رایگان'), ('paid', 'پولی')], default='free', max_length=10),
        ),
    ]
